server:
  port: ${SERVER_PORT}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/backend?charactorEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    hikari:
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    neo4j:
      username: ${NEO_USERNAME}
      password: ${NEO_PASSWORD}
      uri: http://${NEO_HOST}:${NEO_PORT}
  elasticsearch:
    rest:
      uris: http://${ES_HOST}:${ES_PORT}
      username: ${ES_USERNAME}
      password: ${ES_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 1000MB

file:
  uploadFolder: ${UPLOAD_FOLDER}
  staticAccessPath: /static/image/**

python:
  APISwitch: ${API_SWITCH}